public enum S3_GameMessageType
{
    ClientConnectRequest,
    ServerConnectResponse,
    ClientResponseAck,
    ServerTime,
    ClientTimeReceived,
    ServerTimeOffset,
    ServerPlayerPosDR,
    ServerPlayerRotDR,
    ClientPosDR,
    ClientRotDR,
    ServerPlayerDied,
    ServerPlayerHit,
    ServerPlayerSwing,
    ServerPlayerSwitch,
    ServerStartGame,
    ServerNewPlayer,
    ClientSwing,
    ClientSwitch
}